name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: 'Features'
    label: 'Feature'
  - title: 'Fixes'
    label: 'BugFix'
  - title: 'Setting'
    label: 'Setting'
  - title: 'Test'
    label: 'Test'
template: |
  ## 📋 변경점
  $CHANGES
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
change-template: "- $TITLE (#$NUMBER)"
