spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.2:3306/withfestival?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create

custom:
  redis:
    host: 172.17.0.3
    port: 6379