spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao

# 배포 시 내장 레디스 사용하여 테스트 실행
custom:
  redis:
    host: localhost
    port: 6378

webhook:
  slack:
    url: ${custom.webhook.SLACK_DEVELOP_URL}
  discord:
    url: ${custom.webhook.DISCORD_DEVELOP_URL}
