spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_1:3306/withfestival?characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://server.withfestival.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image

custom:
  redis:
    host: redis_1
    port: 6379

webhook:
  slack:
    url: ${custom.webhook.SLACK_PRODUCTION_URL}
  discord:
    url: ${custom.webhook.DISCORD_PRODUCTION_URL}