spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/festival
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true