spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://festival.cmumbmusnz38.ap-northeast-2.rds.amazonaws.com:5432/festival
    username: postgres
    password: millicon!0303
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    s3:
      bucket: millicon-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIASG45PTC6R6KZTD7D
      secretKey: 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
