#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bootsecurity

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/festival
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

file:
  path: C:/image/