spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://withfestval.cevuktsbhaoe.ap-northeast-2.rds.amazonaws.com:5432/withFestval
    username: postgres
    password: millicon!0303
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    s3:
      bucket: millicon
    region:
      static: ap-northeast-2
    credentials:
      accessKey:
      secretKey:
