spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cmumbmusnz38.ap-northeast-2.rds.amazonaws.com:5432/festival
    username: postgres
    password: millicon!0303
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
cloud:
  aws:
    s3:
      bucket: millicon-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIASG45PTC6R6KZTD7D
      secretKey: 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
    stack:
      auto: false
